SET NOCOUNT ON;

/*
 User-entered values
 --------------------------------------------------------------------
 @FORM_ID: Target SCALE form ID
 @ACTION: Action name passed to /UserAction/ExecProc?action=<ACTION>
 @BTN_RESOURCE_VALUE: Label shown in the actions dropdown button
 @MODAL_EDITOR_RESOURCE_VALUE: Label shown for modal editor input
 @POST_INTERNAL_ID_FIELD: Grid column sent as internalID
 @ALLOW_MULTI_SELECT: 1 = allow action on multi-select, 0 = single-select only
 @MODAL: 1 = create modal workflow, 0 = direct post workflow
*/
DECLARE @FORM_ID NUMERIC(5,0) = 10089;

--DECLARE @ACTION NVARCHAR(200) = N'ChgLblPrt';
--DECLARE @BTN_RESOURCE_VALUE NVARCHAR(200) = N'Change Label Printer';
--DECLARE @MODAL_EDITOR_RESOURCE_VALUE NVARCHAR(200) = N'Enter Label Printer';

DECLARE @ACTION NVARCHAR(200) = N'ChgDocPrt';
DECLARE @BTN_RESOURCE_VALUE NVARCHAR(200) = N'Change Document Printer';
DECLARE @MODAL_EDITOR_RESOURCE_VALUE NVARCHAR(200) = N'Enter Document Printer';

DECLARE @POST_INTERNAL_ID_FIELD NVARCHAR(200) = N'WORKSTATION';
DECLARE @ALLOW_MULTI_SELECT BIT = 0;
DECLARE @MODAL BIT = 1;

/*
 Optional user-entered values
 --------------------------------------------------------------------
 @POST_CHANGEVALUE_GRID_FIELD: Grid column sent as changeValue for non-modal actions
 @MODAL_DIALOG_NAME: Name of modal part when @MODAL = 1
 @MODAL_EDITOR_NAME: Name of editor control used for changeValue in modal
 @REQUIRE_SELECTED_ROW: 1 = add/update EnableAction_* on active row change, 0 = skip
 @OVERRIDE_ENABLE_ACTION_PARAM_VALUE: Optional override for EnableAction_* expression
 @ALLOWED_GROUP / @NOT_ALLOWED_GROUP: Security groups for checkpoint assignment
*/
DECLARE @POST_CHANGEVALUE_GRID_FIELD NVARCHAR(200) = @POST_INTERNAL_ID_FIELD;
DECLARE @MODAL_DIALOG_NAME NVARCHAR(200) = @ACTION + N'ModalDialog';
DECLARE @MODAL_EDITOR_NAME NVARCHAR(200) = @ACTION + N'Editor';
DECLARE @REQUIRE_SELECTED_ROW BIT = 1;
DECLARE @OVERRIDE_ENABLE_ACTION_PARAM_VALUE NVARCHAR(400) = NULL;
DECLARE @ALLOWED_GROUP NVARCHAR(128) = N'System';
DECLARE @NOT_ALLOWED_GROUP NVARCHAR(128) = NULL;

/*
 Internal variables
*/
DECLARE @USER_NAME NVARCHAR(200) = SUSER_SNAME();
DECLARE @BTN_RESOURCE_KEY NVARCHAR(200) = UPPER(REPLACE(@BTN_RESOURCE_VALUE, N' ', N''));
DECLARE @MODAL_EDITOR_RESOURCE_KEY NVARCHAR(200) = UPPER(REPLACE(@MODAL_EDITOR_RESOURCE_VALUE, N' ', N''));
DECLARE @POST_URL NVARCHAR(400) = N'/UserAction/ExecProc?action=' + @ACTION;
DECLARE @MAIN_CONTROL_NAME NVARCHAR(200) = N'ListPaneMenuAction' + @ACTION;
DECLARE @MAIN_EVENT_NAME NVARCHAR(200) = CASE WHEN @MODAL = 1 THEN N'_webUi.dialog.showModalDialogByEvent' ELSE N'_webUi.insightListPaneActions.performPostForSelection' END;
DECLARE @SAVE_BUTTON_NAME NVARCHAR(200) = @ACTION + N'SaveButton';
DECLARE @MODAL_FORM_GROUP_NAME NVARCHAR(200) = @MODAL_DIALOG_NAME + N'Form';
DECLARE @MODAL_HEADER_GROUP_NAME NVARCHAR(200) = @MODAL_DIALOG_NAME + N'Header';
DECLARE @MODAL_BODY_GROUP_NAME NVARCHAR(200) = @MODAL_DIALOG_NAME + N'Body';
DECLARE @MODAL_FOOTER_GROUP_NAME NVARCHAR(200) = @MODAL_DIALOG_NAME + N'Footer';
DECLARE @MODAL_INPUT_PARAM_NAME NVARCHAR(300) = N'PostData_Input_' + @MODAL_EDITOR_NAME + N'_changeValue';
DECLARE @PROCESS_STAMP NVARCHAR(200) = N'create-user-action.sql';

DECLARE @SCREEN_ID NUMERIC(9,0);
DECLARE @SCREEN_GROUP_ID NUMERIC(9,0);
DECLARE @MAIN_CONTROL_ID NUMERIC(9,0);
DECLARE @MAIN_EVENT_ID NUMERIC(9,0);
DECLARE @LIST_GRID_EVENT_ID NUMERIC(9,0);
DECLARE @SAVE_EVENT_ID NUMERIC(9,0);
DECLARE @MODAL_PART_ID NUMERIC(9,0);
DECLARE @MODAL_FORM_GROUP_ID NUMERIC(9,0);
DECLARE @MODAL_HEADER_GROUP_ID NUMERIC(9,0);
DECLARE @MODAL_BODY_GROUP_ID NUMERIC(9,0);
DECLARE @MODAL_FOOTER_GROUP_ID NUMERIC(9,0);
DECLARE @MODAL_EDITOR_CONTROL_ID NUMERIC(9,0);
DECLARE @SAVE_BUTTON_CONTROL_ID NUMERIC(9,0);
DECLARE @CHECK_POINT INT;
DECLARE @MAX_CP INT;
DECLARE @ALLOWED_GROUP_ID NUMERIC(9,0);
DECLARE @NOT_ALLOWED_GROUP_ID NUMERIC(9,0);
DECLARE @NEXT_SEQ NUMERIC(9,0);
DECLARE @ENABLE_ACTION_PARAM_NAME NVARCHAR(300) = N'EnableAction_' + @MAIN_CONTROL_NAME;
DECLARE @ENABLE_ACTION_PARAM_VALUE NVARCHAR(400) = ISNULL(@OVERRIDE_ENABLE_ACTION_PARAM_VALUE, @POST_INTERNAL_ID_FIELD + N' !== NULL');
DECLARE @ALLOW_MULTI_SELECT_VALUE NVARCHAR(5) = CASE WHEN @ALLOW_MULTI_SELECT = 1 THEN N'true' ELSE N'false' END;

BEGIN TRY
    BEGIN TRANSACTION;

    PRINT N'=== User Action Installer Started ===';
    PRINT N'Form ID: ' + CAST(@FORM_ID AS NVARCHAR(20));
    PRINT N'Action: ' + @ACTION;
    PRINT N'Modal: ' + CAST(@MODAL AS NVARCHAR(1));

    SELECT @ALLOWED_GROUP_ID = OBJECT_ID
    FROM SECURITY_GROUP
    WHERE SECURITY_GROUP = @ALLOWED_GROUP;

    SELECT @NOT_ALLOWED_GROUP_ID = OBJECT_ID
    FROM SECURITY_GROUP
    WHERE SECURITY_GROUP = @NOT_ALLOWED_GROUP;

    SELECT
        @SCREEN_GROUP_ID = actions_group.OBJECT_ID,
        @SCREEN_ID = s.OBJECT_ID,
        @LIST_GRID_EVENT_ID = list_control_event.OBJECT_ID
    FROM MAIN_UI_SCREEN s
    OUTER APPLY (
        SELECT TOP 1 sp.OBJECT_ID
        FROM SCREEN_PART sp
        WHERE sp.SCREEN_ID = s.OBJECT_ID
            AND sp.PART_NAME = N'InsightMenuPane'
            AND sp.ACTIVE = N'Y'
    ) AS menu_part
    OUTER APPLY (
        SELECT TOP 1 sg.OBJECT_ID
        FROM SCREEN_GROUP sg
        WHERE sg.SCREEN_PART_ID = menu_part.OBJECT_ID
            AND sg.GROUP_NAME = N'InsightMenuActionsDropdown'
            AND sg.ACTIVE = N'Y'
    ) AS actions_group
    OUTER APPLY (
        SELECT TOP 1 sp.OBJECT_ID
        FROM SCREEN_PART sp
        WHERE sp.SCREEN_ID = s.OBJECT_ID
            AND sp.PART_NAME = N'ListPane'
            AND sp.ACTIVE = N'Y'
    ) AS list_part
    OUTER APPLY (
        SELECT TOP 1 sg.OBJECT_ID
        FROM SCREEN_GROUP sg
        WHERE sg.SCREEN_PART_ID = list_part.OBJECT_ID
            AND sg.GROUP_NAME = N'ListPanePanel'
            AND sg.ACTIVE = N'Y'
    ) AS list_panel_group
    OUTER APPLY (
        SELECT TOP 1 sc.OBJECT_ID
        FROM SCREEN_CONTROL sc
        WHERE sc.SCREEN_GROUP_ID = list_panel_group.OBJECT_ID
            AND sc.CONTROL_NAME = N'ListPaneDataGrid'
            AND sc.ACTIVE = N'Y'
    ) AS list_control
    OUTER APPLY (
        SELECT TOP 1 sce.OBJECT_ID
        FROM SCREEN_CONTROL_EVENT sce
        WHERE sce.SCREEN_CONTROL_ID = list_control.OBJECT_ID
            AND sce.EVENT_ID = N'iggridselectionactiverowchanged'
            AND sce.ACTIVE = N'Y'
    ) AS list_control_event
    WHERE s.FORM_ID = @FORM_ID
        AND s.ACTIVE = N'Y';

    IF @SCREEN_ID IS NULL OR @SCREEN_GROUP_ID IS NULL
        THROW 50001, 'Unable to locate active screen/actions dropdown for FORM_ID.', 1;

    PRINT N'Target screen found. SCREEN_ID=' + CAST(@SCREEN_ID AS NVARCHAR(20)) + N', ACTIONS_GROUP_ID=' + CAST(@SCREEN_GROUP_ID AS NVARCHAR(20));

    IF NOT EXISTS (
        SELECT 1 FROM RESOURCE_FILE_BASE
        WHERE RESOURCE_LANGUAGE = N'en-US' AND RESOURCE_KEY = @BTN_RESOURCE_KEY
    )
    AND NOT EXISTS (
        SELECT 1 FROM RESOURCE_FILE_CUSTOM
        WHERE RESOURCE_LANGUAGE = N'en-US' AND RESOURCE_KEY = @BTN_RESOURCE_KEY
    )
    BEGIN
        INSERT INTO RESOURCE_FILE_CUSTOM (
            PARENT, RESOURCE_LANGUAGE, RESOURCE_GROUP, RESOURCE_KEY, TEXT, FIELD_LENGTH, DECIMAL_POS,
            USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP
        )
        VALUES (
            0, N'en-US', N'Text', @BTN_RESOURCE_KEY, @BTN_RESOURCE_VALUE, 0, 0,
            0.00000, 0.00000, @USER_NAME, @PROCESS_STAMP, GETUTCDATE()
        );

        PRINT N'Inserted button resource key: ' + @BTN_RESOURCE_KEY;
    END
    ELSE
    BEGIN
        PRINT N'Button resource key already exists: ' + @BTN_RESOURCE_KEY;
    END

    IF @MODAL = 1
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM RESOURCE_FILE_BASE
            WHERE RESOURCE_LANGUAGE = N'en-US' AND RESOURCE_KEY = @MODAL_EDITOR_RESOURCE_KEY
        )
        AND NOT EXISTS (
            SELECT 1 FROM RESOURCE_FILE_CUSTOM
            WHERE RESOURCE_LANGUAGE = N'en-US' AND RESOURCE_KEY = @MODAL_EDITOR_RESOURCE_KEY
        )
        BEGIN
            INSERT INTO RESOURCE_FILE_CUSTOM (
                PARENT, RESOURCE_LANGUAGE, RESOURCE_GROUP, RESOURCE_KEY, TEXT, FIELD_LENGTH, DECIMAL_POS,
                USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP
            )
            VALUES (
                0, N'en-US', N'Text', @MODAL_EDITOR_RESOURCE_KEY, @MODAL_EDITOR_RESOURCE_VALUE, 0, 0,
                0.00000, 0.00000, @USER_NAME, @PROCESS_STAMP, GETUTCDATE()
            );

            PRINT N'Inserted modal editor resource key: ' + @MODAL_EDITOR_RESOURCE_KEY;
        END
        ELSE
        BEGIN
            PRINT N'Modal editor resource key already exists: ' + @MODAL_EDITOR_RESOURCE_KEY;
        END
    END

    SELECT @CHECK_POINT = CHECK_POINT
    FROM SECURITY_CHECKPOINT
    WHERE FORM_ID = @FORM_ID
            AND RESOURCE_FILE_KEY = @BTN_RESOURCE_KEY;

    IF @CHECK_POINT IS NULL
    BEGIN
        SELECT @CHECK_POINT = ISNULL(MAX(CHECK_POINT), 0) + 1
        FROM SECURITY_CHECKPOINT
        WHERE FORM_ID = @FORM_ID;

        INSERT INTO SECURITY_CHECKPOINT (
            FORM_ID, CHECK_POINT, RESOURCE_FILE_KEY, SYSTEM_CREATED, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP
        )
        VALUES (
            @FORM_ID, @CHECK_POINT, @BTN_RESOURCE_KEY, N'N', @USER_NAME, @PROCESS_STAMP, GETUTCDATE()
        );

        PRINT N'Inserted security checkpoint ' + CAST(@CHECK_POINT AS NVARCHAR(10)) + N' for resource ' + @BTN_RESOURCE_KEY;
    END
    ELSE
    BEGIN
        PRINT N'Using existing security checkpoint ' + CAST(@CHECK_POINT AS NVARCHAR(10)) + N' for resource ' + @BTN_RESOURCE_KEY;
    END

    SELECT @MAX_CP = MAX(CHECK_POINT)
    FROM SECURITY_CHECKPOINT
    WHERE FORM_ID = @FORM_ID;

    UPDATE sec
    SET sec.SEC_VALUES = CASE
        WHEN LEN(sec.SEC_VALUES) < @MAX_CP THEN sec.SEC_VALUES + REPLICATE(N'-', @MAX_CP - LEN(sec.SEC_VALUES))
        ELSE sec.SEC_VALUES
    END
    FROM SECURITY sec
    WHERE sec.FORM_ID = @FORM_ID;

    IF @ALLOWED_GROUP IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM SECURITY sec
            WHERE sec.FORM_ID = @FORM_ID
              AND (
                    (@ALLOWED_GROUP = N'System' AND sec.SECURITY_LEVEL = N'System' AND sec.USER_NAME = N'System')
                 OR (@ALLOWED_GROUP <> N'System' AND (
                        (sec.SECURITY_GROUP_ID IS NOT NULL AND sec.SECURITY_GROUP_ID = @ALLOWED_GROUP_ID)
                     OR (sec.SECURITY_LEVEL = N'Group' AND sec.USER_NAME = @ALLOWED_GROUP)
                 ))
              )
        )
        BEGIN
            INSERT INTO SECURITY (
                FORM_ID, SECURITY_LEVEL, USER_NAME, SEC_VALUES, SYSTEM_CREATED,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, SECURITY_GROUP_ID
            )
            VALUES (
                @FORM_ID,
                CASE WHEN @ALLOWED_GROUP = N'System' THEN N'System' ELSE N'Group' END,
                @ALLOWED_GROUP,
                REPLICATE(N'-', @MAX_CP),
                N'N',
                NULL, NULL, NULL, NULL, NULL, 0, 0, 0,
                @USER_NAME, @PROCESS_STAMP, GETUTCDATE(),
                CASE WHEN @ALLOWED_GROUP = N'System' THEN NULL ELSE @ALLOWED_GROUP_ID END
            );

            PRINT N'Inserted SECURITY row for allowed group: ' + @ALLOWED_GROUP;
        END

        UPDATE sec
        SET sec.SEC_VALUES = STUFF(
            CASE WHEN LEN(sec.SEC_VALUES) >= @CHECK_POINT
                 THEN sec.SEC_VALUES
                 ELSE sec.SEC_VALUES + REPLICATE(N'-', @CHECK_POINT - LEN(sec.SEC_VALUES))
            END,
            @CHECK_POINT, 1, N'Y'
        )
        FROM SECURITY sec
        WHERE sec.FORM_ID = @FORM_ID
          AND (
                     (@ALLOWED_GROUP = N'System' AND sec.SECURITY_LEVEL = N'System' AND sec.USER_NAME = N'System')
                 OR
                (sec.SECURITY_GROUP_ID IS NOT NULL AND sec.SECURITY_GROUP_ID = @ALLOWED_GROUP_ID)
             OR (sec.SECURITY_LEVEL = N'Group' AND sec.USER_NAME = @ALLOWED_GROUP)
          );
    END

    IF @NOT_ALLOWED_GROUP IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM SECURITY sec
            WHERE sec.FORM_ID = @FORM_ID
              AND (
                    (@NOT_ALLOWED_GROUP = N'System' AND sec.SECURITY_LEVEL = N'System' AND sec.USER_NAME = N'System')
                 OR (@NOT_ALLOWED_GROUP <> N'System' AND (
                        (sec.SECURITY_GROUP_ID IS NOT NULL AND sec.SECURITY_GROUP_ID = @NOT_ALLOWED_GROUP_ID)
                     OR (sec.SECURITY_LEVEL = N'Group' AND sec.USER_NAME = @NOT_ALLOWED_GROUP)
                 ))
              )
        )
        BEGIN
            INSERT INTO SECURITY (
                FORM_ID, SECURITY_LEVEL, USER_NAME, SEC_VALUES, SYSTEM_CREATED,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, SECURITY_GROUP_ID
            )
            VALUES (
                @FORM_ID,
                CASE WHEN @NOT_ALLOWED_GROUP = N'System' THEN N'System' ELSE N'Group' END,
                @NOT_ALLOWED_GROUP,
                REPLICATE(N'-', @MAX_CP),
                N'N',
                NULL, NULL, NULL, NULL, NULL, 0, 0, 0,
                @USER_NAME, @PROCESS_STAMP, GETUTCDATE(),
                CASE WHEN @NOT_ALLOWED_GROUP = N'System' THEN NULL ELSE @NOT_ALLOWED_GROUP_ID END
            );

            PRINT N'Inserted SECURITY row for restricted group: ' + @NOT_ALLOWED_GROUP;
        END

        UPDATE sec
        SET sec.SEC_VALUES = STUFF(
            CASE WHEN LEN(sec.SEC_VALUES) >= @CHECK_POINT
                 THEN sec.SEC_VALUES
                 ELSE sec.SEC_VALUES + REPLICATE(N'-', @CHECK_POINT - LEN(sec.SEC_VALUES))
            END,
            @CHECK_POINT, 1, N'N'
        )
        FROM SECURITY sec
        WHERE sec.FORM_ID = @FORM_ID
          AND (
                (sec.SECURITY_GROUP_ID IS NOT NULL AND sec.SECURITY_GROUP_ID = @NOT_ALLOWED_GROUP_ID)
             OR (sec.SECURITY_LEVEL = N'System' AND sec.USER_NAME = N'System')
             OR (sec.SECURITY_LEVEL = N'Group' AND sec.USER_NAME = @NOT_ALLOWED_GROUP)
          );
    END

    UPDATE sec
    SET sec.SEC_VALUES = STUFF(
        CASE WHEN LEN(sec.SEC_VALUES) >= @CHECK_POINT
             THEN sec.SEC_VALUES
             ELSE sec.SEC_VALUES + REPLICATE(N'-', @CHECK_POINT - LEN(sec.SEC_VALUES))
        END,
        @CHECK_POINT, 1, N'-'
    )
    FROM SECURITY sec
    WHERE sec.FORM_ID = @FORM_ID
      AND NOT (
            (sec.SECURITY_GROUP_ID IS NOT NULL AND sec.SECURITY_GROUP_ID IN (@ALLOWED_GROUP_ID, @NOT_ALLOWED_GROUP_ID))
         OR (sec.SECURITY_LEVEL = N'System' AND sec.USER_NAME = N'System')
         OR (sec.SECURITY_LEVEL = N'Group' AND sec.USER_NAME IN (@ALLOWED_GROUP, @NOT_ALLOWED_GROUP))
      );

    PRINT N'Security checkpoint permissions updated.';

    SELECT @MAIN_CONTROL_ID = OBJECT_ID
    FROM SCREEN_CONTROL
    WHERE SCREEN_GROUP_ID = @SCREEN_GROUP_ID
      AND CONTROL_NAME = @MAIN_CONTROL_NAME;

    IF @MAIN_CONTROL_ID IS NULL
    BEGIN
        SELECT @NEXT_SEQ = ISNULL(MAX(SEQUENCE), 0) + 100
        FROM SCREEN_CONTROL
        WHERE SCREEN_GROUP_ID = @SCREEN_GROUP_ID;

        INSERT INTO SCREEN_CONTROL (
            SCREEN_GROUP_ID, CONTROL_NAME, RESOURCE_KEY, CONTROL_TYPE, USER_DEF7, USER_DEF8,
            USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, SYSTEM_CREATED, SEQUENCE, ACTIVE,
            TOOL_TIP_RESOURCE_KEY, CONTROL_CSS_CLASS
        )
        VALUES (
            @SCREEN_GROUP_ID, @MAIN_CONTROL_NAME, @BTN_RESOURCE_KEY, 150, 0.00000, 0.00000,
            @USER_NAME, N'ScreenControlApiController.Save', GETUTCDATE(), N'N', @NEXT_SEQ, N'Y',
            @BTN_RESOURCE_KEY, N'dropdownaction'
        );

        SET @MAIN_CONTROL_ID = SCOPE_IDENTITY();
        PRINT N'Inserted action control. CONTROL_ID=' + CAST(@MAIN_CONTROL_ID AS NVARCHAR(20));
    END
    ELSE
    BEGIN
        PRINT N'Action control already exists. CONTROL_ID=' + CAST(@MAIN_CONTROL_ID AS NVARCHAR(20));
    END

    IF @REQUIRE_SELECTED_ROW = 1 AND @LIST_GRID_EVENT_ID IS NOT NULL
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM SCREEN_CONTROL_EVENT_PARAMETERS
            WHERE SCREEN_CONTROL_EVENT_ID = @LIST_GRID_EVENT_ID
              AND PARAMETER_NAME = @ENABLE_ACTION_PARAM_NAME
              AND ACTIVE = N'Y'
        )
        BEGIN
            UPDATE SCREEN_CONTROL_EVENT_PARAMETERS
            SET PARAMETER_VALUE = @ENABLE_ACTION_PARAM_VALUE,
                USER_STAMP = @USER_NAME,
                PROCESS_STAMP = N'ScreenControlEventParametersApiController.Save',
                DATE_TIME_STAMP = GETUTCDATE()
            WHERE SCREEN_CONTROL_EVENT_ID = @LIST_GRID_EVENT_ID
              AND PARAMETER_NAME = @ENABLE_ACTION_PARAM_NAME
              AND ACTIVE = N'Y';

            PRINT N'Updated list grid enable-action param: ' + @ENABLE_ACTION_PARAM_NAME + N' = ' + @ENABLE_ACTION_PARAM_VALUE;
        END
        ELSE
        BEGIN
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (
                SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED
            )
            VALUES (
                @LIST_GRID_EVENT_ID, @ENABLE_ACTION_PARAM_NAME, @ENABLE_ACTION_PARAM_VALUE,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N'
            );

            PRINT N'Inserted list grid enable-action param: ' + @ENABLE_ACTION_PARAM_NAME + N' = ' + @ENABLE_ACTION_PARAM_VALUE;
        END
    END
    ELSE IF @REQUIRE_SELECTED_ROW = 0
    BEGIN
        PRINT N'Skipping enable-action parameter setup because @REQUIRE_SELECTED_ROW = 0.';
    END
    ELSE
    BEGIN
        PRINT N'Warning: ListPaneDataGrid iggridselectionactiverowchanged event not found. Skipping enable-action parameter setup.';
    END

    IF NOT EXISTS (
        SELECT 1 FROM SCREEN_CONTROL_ATTRIBUTES
        WHERE SCREEN_CONTROL_ID = @MAIN_CONTROL_ID
          AND ATTRIBUTE_NAME = N'data-allowOnMultiSelect'
          AND ACTIVE = N'Y'
    )
    BEGIN
        INSERT INTO SCREEN_CONTROL_ATTRIBUTES (
            SCREEN_CONTROL_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, ACTIVE, SYSTEM_CREATED,
            USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
            USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, IS_CONTROL_PROPERTY,
            TOKEN1, TOKEN2, TOKEN3, TOKEN4, TOKEN5, TOKEN6, TOKEN7, TOKEN8, TOKEN9, TOKEN10
        )
        VALUES (
            @MAIN_CONTROL_ID, N'data-allowOnMultiSelect', @ALLOW_MULTI_SELECT_VALUE, N'Y', N'N',
            NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
            @USER_NAME, N'ScreenControlAttributesApiController.Save', GETUTCDATE(), N'N',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
        );
    END

    IF NOT EXISTS (
        SELECT 1 FROM SCREEN_CONTROL_ATTRIBUTES
        WHERE SCREEN_CONTROL_ID = @MAIN_CONTROL_ID
          AND ATTRIBUTE_NAME = N'data-securityCheckpoint'
          AND ACTIVE = N'Y'
    )
    BEGIN
        INSERT INTO SCREEN_CONTROL_ATTRIBUTES (
            SCREEN_CONTROL_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, ACTIVE, SYSTEM_CREATED,
            USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
            USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, IS_CONTROL_PROPERTY,
            TOKEN1, TOKEN2, TOKEN3, TOKEN4, TOKEN5, TOKEN6, TOKEN7, TOKEN8, TOKEN9, TOKEN10
        )
        VALUES (
            @MAIN_CONTROL_ID, N'data-securityCheckpoint', CAST(@CHECK_POINT AS NVARCHAR(50)), N'Y', N'N',
            NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
            @USER_NAME, N'ScreenControlAttributesApiController.Save', GETUTCDATE(), N'N',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
        );
    END

    SELECT @MAIN_EVENT_ID = OBJECT_ID
    FROM SCREEN_CONTROL_EVENT
    WHERE SCREEN_CONTROL_ID = @MAIN_CONTROL_ID
      AND EVENT_ID = N'click'
      AND EVENT_NAME = @MAIN_EVENT_NAME
      AND ACTIVE = N'Y';

    IF @MAIN_EVENT_ID IS NULL
    BEGIN
        INSERT INTO SCREEN_CONTROL_EVENT (
            SCREEN_CONTROL_ID, EVENT_ID, EVENT_NAME, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4,
            USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP,
            DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED, GRID_COLUMN
        )
        VALUES (
            @MAIN_CONTROL_ID, N'click', @MAIN_EVENT_NAME, NULL, NULL, NULL, NULL,
            NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventApiController.Save',
            GETUTCDATE(), N'Y', N'N', NULL
        );

        SET @MAIN_EVENT_ID = SCOPE_IDENTITY();
        PRINT N'Inserted main click event. EVENT_ID=' + CAST(@MAIN_EVENT_ID AS NVARCHAR(20));
    END
    ELSE
    BEGIN
        PRINT N'Main click event already exists. EVENT_ID=' + CAST(@MAIN_EVENT_ID AS NVARCHAR(20));
    END

    IF @MODAL = 1
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS
            WHERE SCREEN_CONTROL_EVENT_ID = @MAIN_EVENT_ID
              AND PARAMETER_NAME = N'ModalDialogName'
              AND ACTIVE = N'Y'
        )
        BEGIN
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (
                SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED
            )
            VALUES (
                @MAIN_EVENT_ID, N'ModalDialogName', @MODAL_DIALOG_NAME,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N'
            );
        END

        SELECT @MODAL_PART_ID = OBJECT_ID
        FROM SCREEN_PART
        WHERE SCREEN_ID = @SCREEN_ID
          AND PART_NAME = @MODAL_DIALOG_NAME
          AND ACTIVE = N'Y';

        IF @MODAL_PART_ID IS NULL
        BEGIN
            SELECT @NEXT_SEQ = ISNULL(MAX(SEQUENCE), 0) + 100
            FROM SCREEN_PART
            WHERE SCREEN_ID = @SCREEN_ID;

            INSERT INTO SCREEN_PART (
                SCREEN_ID, PART_NAME, RESOURCE_KEY, PART_TYPE,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, SYSTEM_CREATED, SEQUENCE, ACTIVE,
                DEFAULT_ACTION, DIV_CSS_CLASS, PARTIAL_VIEW
            )
            VALUES (
                @SCREEN_ID, @MODAL_DIALOG_NAME, NULL, 20,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenPartApiController.Save', GETUTCDATE(), N'N', @NEXT_SEQ, N'Y',
                @SAVE_BUTTON_NAME, NULL, N'Y'
            );

            SET @MODAL_PART_ID = SCOPE_IDENTITY();
            PRINT N'Inserted modal screen part. PART_ID=' + CAST(@MODAL_PART_ID AS NVARCHAR(20));
        END
        ELSE
        BEGIN
            PRINT N'Modal screen part already exists. PART_ID=' + CAST(@MODAL_PART_ID AS NVARCHAR(20));
        END

        SELECT @MODAL_FORM_GROUP_ID = OBJECT_ID
        FROM SCREEN_GROUP
        WHERE SCREEN_PART_ID = @MODAL_PART_ID
          AND GROUP_NAME = @MODAL_FORM_GROUP_NAME
          AND ACTIVE = N'Y';

        IF @MODAL_FORM_GROUP_ID IS NULL
        BEGIN
            INSERT INTO SCREEN_GROUP (
                SCREEN_PART_ID, GROUP_NAME, RESOURCE_KEY,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP,
                PARENT_GROUP_ID, NESTED_GROUP_UNIT, GROUP_TYPE, SYSTEM_CREATED, SEQUENCE, ACTIVE,
                ROW_CSS_CLASS, DEFAULT_ACTION, DIV_CSS_CLASS, FIXED_TO_TOP, CONTENT_LOADING_TYPE
            )
            VALUES (
                @MODAL_PART_ID, @MODAL_FORM_GROUP_NAME, NULL,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenGroupApiController.Save', GETUTCDATE(),
                NULL, 1, 90, N'N', 2500, N'Y',
                NULL, NULL, N'form-horizontal', N'N', 0
            );

            SET @MODAL_FORM_GROUP_ID = SCOPE_IDENTITY();

            UPDATE SCREEN_GROUP
            SET NESTED_GROUP_UNIT = @MODAL_FORM_GROUP_ID
            WHERE OBJECT_ID = @MODAL_FORM_GROUP_ID;

            PRINT N'Inserted modal form group. GROUP_ID=' + CAST(@MODAL_FORM_GROUP_ID AS NVARCHAR(20));
        END

        SELECT @MODAL_HEADER_GROUP_ID = OBJECT_ID
        FROM SCREEN_GROUP
        WHERE SCREEN_PART_ID = @MODAL_PART_ID
          AND GROUP_NAME = @MODAL_HEADER_GROUP_NAME
          AND ACTIVE = N'Y';

        IF @MODAL_HEADER_GROUP_ID IS NULL
        BEGIN
            INSERT INTO SCREEN_GROUP (
                SCREEN_PART_ID, GROUP_NAME, RESOURCE_KEY,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP,
                PARENT_GROUP_ID, NESTED_GROUP_UNIT, GROUP_TYPE, SYSTEM_CREATED, SEQUENCE, ACTIVE,
                ROW_CSS_CLASS, DEFAULT_ACTION, DIV_CSS_CLASS, FIXED_TO_TOP, CONTENT_LOADING_TYPE
            )
            VALUES (
                @MODAL_PART_ID, @MODAL_HEADER_GROUP_NAME, @BTN_RESOURCE_KEY,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenGroupApiController.Save', GETUTCDATE(),
                @MODAL_FORM_GROUP_ID, @MODAL_FORM_GROUP_ID, 110, N'N', 2500, N'Y',
                NULL, NULL, NULL, N'N', 0
            );

            SET @MODAL_HEADER_GROUP_ID = SCOPE_IDENTITY();
        END

        SELECT @MODAL_BODY_GROUP_ID = OBJECT_ID
        FROM SCREEN_GROUP
        WHERE SCREEN_PART_ID = @MODAL_PART_ID
          AND GROUP_NAME = @MODAL_BODY_GROUP_NAME
          AND ACTIVE = N'Y';

        IF @MODAL_BODY_GROUP_ID IS NULL
        BEGIN
            INSERT INTO SCREEN_GROUP (
                SCREEN_PART_ID, GROUP_NAME, RESOURCE_KEY,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP,
                PARENT_GROUP_ID, NESTED_GROUP_UNIT, GROUP_TYPE, SYSTEM_CREATED, SEQUENCE, ACTIVE,
                ROW_CSS_CLASS, DEFAULT_ACTION, DIV_CSS_CLASS, FIXED_TO_TOP, CONTENT_LOADING_TYPE
            )
            VALUES (
                @MODAL_PART_ID, @MODAL_BODY_GROUP_NAME, NULL,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenGroupApiController.Save', GETUTCDATE(),
                @MODAL_FORM_GROUP_ID, @MODAL_FORM_GROUP_ID, 120, N'N', 5000, N'Y',
                NULL, NULL, NULL, N'N', 0
            );

            SET @MODAL_BODY_GROUP_ID = SCOPE_IDENTITY();
        END

        SELECT @MODAL_FOOTER_GROUP_ID = OBJECT_ID
        FROM SCREEN_GROUP
        WHERE SCREEN_PART_ID = @MODAL_PART_ID
          AND GROUP_NAME = @MODAL_FOOTER_GROUP_NAME
          AND ACTIVE = N'Y';

        IF @MODAL_FOOTER_GROUP_ID IS NULL
        BEGIN
            INSERT INTO SCREEN_GROUP (
                SCREEN_PART_ID, GROUP_NAME, RESOURCE_KEY,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP,
                PARENT_GROUP_ID, NESTED_GROUP_UNIT, GROUP_TYPE, SYSTEM_CREATED, SEQUENCE, ACTIVE,
                ROW_CSS_CLASS, DEFAULT_ACTION, DIV_CSS_CLASS, FIXED_TO_TOP, CONTENT_LOADING_TYPE
            )
            VALUES (
                @MODAL_PART_ID, @MODAL_FOOTER_GROUP_NAME, NULL,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenGroupApiController.Save', GETUTCDATE(),
                @MODAL_FORM_GROUP_ID, @MODAL_FORM_GROUP_ID, 130, N'N', 7500, N'Y',
                NULL, NULL, NULL, N'N', 0
            );

            SET @MODAL_FOOTER_GROUP_ID = SCOPE_IDENTITY();
        END

        SELECT @MODAL_EDITOR_CONTROL_ID = OBJECT_ID
        FROM SCREEN_CONTROL
        WHERE SCREEN_GROUP_ID = @MODAL_BODY_GROUP_ID
          AND CONTROL_NAME = @MODAL_EDITOR_NAME
          AND ACTIVE = N'Y';

        IF @MODAL_EDITOR_CONTROL_ID IS NULL
        BEGIN
            INSERT INTO SCREEN_CONTROL (
                SCREEN_GROUP_ID, CONTROL_NAME, RESOURCE_KEY, CONTROL_TYPE,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP,
                LABEL_ORIENTATION, SYSTEM_CREATED, DATA_SOURCE_TYPE, DATA_SOURCE, SEQUENCE,
                DEFAULT_STATE, ACTIVE, TOOL_TIP_RESOURCE_KEY, DEFAULT_ACTION, SCREEN_GROUP_COLUMN_ID,
                DIV_CSS_CLASS, CONTROL_CSS_CLASS, TEMPLATE_NAME
            )
            VALUES (
                @MODAL_BODY_GROUP_ID, @MODAL_EDITOR_NAME, @MODAL_EDITOR_RESOURCE_KEY, 10,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenControlApiController.Save', GETUTCDATE(),
                40, N'N', NULL, NULL, 2500,
                NULL, N'Y', NULL, NULL, NULL,
                N'basiccriteriarow', NULL, NULL
            );

            SET @MODAL_EDITOR_CONTROL_ID = SCOPE_IDENTITY();
        END

        SELECT @SAVE_BUTTON_CONTROL_ID = OBJECT_ID
        FROM SCREEN_CONTROL
        WHERE SCREEN_GROUP_ID = @MODAL_FOOTER_GROUP_ID
          AND CONTROL_NAME = @SAVE_BUTTON_NAME
          AND ACTIVE = N'Y';

        IF @SAVE_BUTTON_CONTROL_ID IS NULL
        BEGIN
            INSERT INTO SCREEN_CONTROL (
                SCREEN_GROUP_ID, CONTROL_NAME, RESOURCE_KEY, CONTROL_TYPE,
                USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8,
                USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP,
                LABEL_ORIENTATION, SYSTEM_CREATED, DATA_SOURCE_TYPE, DATA_SOURCE, SEQUENCE,
                DEFAULT_STATE, ACTIVE, TOOL_TIP_RESOURCE_KEY, DEFAULT_ACTION, SCREEN_GROUP_COLUMN_ID,
                DIV_CSS_CLASS, CONTROL_CSS_CLASS, TEMPLATE_NAME
            )
            VALUES (
                @MODAL_FOOTER_GROUP_ID, @SAVE_BUTTON_NAME, N'BTN_SAVE', 100,
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenControlApiController.Save', GETUTCDATE(),
                NULL, N'N', NULL, NULL, 2500,
                NULL, N'Y', NULL, NULL, NULL,
                N'displayinline', N'btn btn-default', NULL
            );

            SET @SAVE_BUTTON_CONTROL_ID = SCOPE_IDENTITY();
        END

        SELECT @SAVE_EVENT_ID = OBJECT_ID
        FROM SCREEN_CONTROL_EVENT
        WHERE SCREEN_CONTROL_ID = @SAVE_BUTTON_CONTROL_ID
          AND EVENT_ID = N'click'
          AND EVENT_NAME = N'_webUi.insightListPaneActions.modalDialogPerformPostForSelection'
          AND ACTIVE = N'Y';

        IF @SAVE_EVENT_ID IS NULL
        BEGIN
            INSERT INTO SCREEN_CONTROL_EVENT (
                SCREEN_CONTROL_ID, EVENT_ID, EVENT_NAME, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4,
                USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP,
                DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED, GRID_COLUMN
            )
            VALUES (
                @SAVE_BUTTON_CONTROL_ID, N'click', N'_webUi.insightListPaneActions.modalDialogPerformPostForSelection',
                NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000,
                @USER_NAME, N'ScreenControlEventApiController.Save', GETUTCDATE(), N'Y', N'N', NULL
            );

            SET @SAVE_EVENT_ID = SCOPE_IDENTITY();
        END

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @SAVE_EVENT_ID AND PARAMETER_NAME = N'POSTServiceURL' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@SAVE_EVENT_ID, N'POSTServiceURL', @POST_URL, NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @SAVE_EVENT_ID AND PARAMETER_NAME = N'Post_ErrorCallback' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@SAVE_EVENT_ID, N'Post_ErrorCallback', N'_webUi.insightListPaneActions.postMethodErrorCallbackHandler', NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @SAVE_EVENT_ID AND PARAMETER_NAME = N'Post_SuccessCallback' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@SAVE_EVENT_ID, N'Post_SuccessCallback', N'_webUi.insightListPaneActions.refreshGridAndCallDefaultSuccessCallback', NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @SAVE_EVENT_ID AND PARAMETER_NAME = N'ModalDialogName' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@SAVE_EVENT_ID, N'ModalDialogName', @MODAL_DIALOG_NAME, NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @SAVE_EVENT_ID AND PARAMETER_NAME = N'PostData_Grid_ListPaneDataGrid_internalID' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@SAVE_EVENT_ID, N'PostData_Grid_ListPaneDataGrid_internalID', @POST_INTERNAL_ID_FIELD, NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @SAVE_EVENT_ID AND PARAMETER_NAME = @MODAL_INPUT_PARAM_NAME AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@SAVE_EVENT_ID, @MODAL_INPUT_PARAM_NAME, N'value', NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        PRINT N'Modal components and save-post wiring completed.';
    END
    ELSE
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @MAIN_EVENT_ID AND PARAMETER_NAME = N'POSTServiceURL' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@MAIN_EVENT_ID, N'POSTServiceURL', @POST_URL, NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @MAIN_EVENT_ID AND PARAMETER_NAME = N'Post_ErrorCallback' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@MAIN_EVENT_ID, N'Post_ErrorCallback', N'_webUi.insightListPaneActions.postMethodErrorCallbackHandler', NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @MAIN_EVENT_ID AND PARAMETER_NAME = N'Post_SuccessCallback' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@MAIN_EVENT_ID, N'Post_SuccessCallback', N'_webUi.insightListPaneActions.refreshGridAndCallDefaultSuccessCallback', NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @MAIN_EVENT_ID AND PARAMETER_NAME = N'PostData_Grid_ListPaneDataGrid_internalID' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@MAIN_EVENT_ID, N'PostData_Grid_ListPaneDataGrid_internalID', @POST_INTERNAL_ID_FIELD, NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        IF NOT EXISTS (SELECT 1 FROM SCREEN_CONTROL_EVENT_PARAMETERS WHERE SCREEN_CONTROL_EVENT_ID = @MAIN_EVENT_ID AND PARAMETER_NAME = N'PostData_Grid_ListPaneDataGrid_changeValue' AND ACTIVE = N'Y')
            INSERT INTO SCREEN_CONTROL_EVENT_PARAMETERS (SCREEN_CONTROL_EVENT_ID, PARAMETER_NAME, PARAMETER_VALUE, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, ACTIVE, SYSTEM_CREATED)
            VALUES (@MAIN_EVENT_ID, N'PostData_Grid_ListPaneDataGrid_changeValue', @POST_CHANGEVALUE_GRID_FIELD, NULL, NULL, NULL, NULL, NULL, NULL, 0.00000, 0.00000, @USER_NAME, N'ScreenControlEventParametersApiController.Save', GETUTCDATE(), N'Y', N'N');

        PRINT N'Non-modal post wiring completed.';
    END

    COMMIT TRANSACTION;

    PRINT N'=== User Action Installer Completed Successfully ===';
    PRINT N'Button Resource Key: ' + @BTN_RESOURCE_KEY;
    IF @MODAL = 1
        PRINT N'Modal Editor Resource Key: ' + @MODAL_EDITOR_RESOURCE_KEY;
    PRINT N'Control Name: ' + @MAIN_CONTROL_NAME;
    PRINT N'Action URL: ' + @POST_URL;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;

    DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrNum INT = ERROR_NUMBER();
    DECLARE @ErrLine INT = ERROR_LINE();
    DECLARE @ErrProc NVARCHAR(200) = ERROR_PROCEDURE();

    PRINT N'=== User Action Installer Failed ===';
    PRINT N'Error Number: ' + CAST(@ErrNum AS NVARCHAR(20));
    PRINT N'Error Line: ' + CAST(@ErrLine AS NVARCHAR(20));
    PRINT N'Error Procedure: ' + ISNULL(@ErrProc, N'<dynamic SQL / batch>');
    PRINT N'Error Message: ' + @ErrMsg;

    THROW;
END CATCH;
