SET NOCOUNT ON;

/*
 User-entered values
 --------------------------------------------------------------------
 @FORM_ID: Target SCALE form ID
 @ACTION: Action name passed to /UserAction/ExecProc?action=<ACTION>
 @RESOURCE_VALUE: Label used in the actions dropdown
*/
DECLARE @FORM_ID NUMERIC(5,0) = 10089;
DECLARE @ACTION NVARCHAR(200) = N'ChangeWorkstationLabel';
DECLARE @RESOURCE_VALUE NVARCHAR(200) = N'Change Label Printer';

/*
 Optional user-entered values
 --------------------------------------------------------------------
 @MODAL_DIALOG_NAME should match the one used by create-user-action.sql
*/
DECLARE @OVERRIDE_MAIN_CONTROL_NAME NVARCHAR(200) = NULL;
DECLARE @OVERRIDE_MODAL_DIALOG_NAME NVARCHAR(200) = NULL;

/*
 Internal variables
*/
DECLARE @USER_NAME NVARCHAR(200) = SUSER_SNAME();
DECLARE @RESOURCE_KEY NVARCHAR(200) = UPPER(REPLACE(@RESOURCE_VALUE, N' ', N''));
DECLARE @ACTION_NAME_CANONICAL NVARCHAR(200) = UPPER(REPLACE(REPLACE(REPLACE(@ACTION, N' ', N''), N'_', N''), N'-', N''));
DECLARE @ACTION_NAME_HASH NVARCHAR(8) = RIGHT(CONVERT(NVARCHAR(32), HASHBYTES('MD5', @ACTION), 2), 8);
DECLARE @ACTION_NAME_TOKEN NVARCHAR(18) = LEFT(@ACTION_NAME_CANONICAL, 10) + @ACTION_NAME_HASH;
DECLARE @MAIN_CONTROL_NAME NVARCHAR(200) = ISNULL(@OVERRIDE_MAIN_CONTROL_NAME, N'UA_ACT_' + @ACTION_NAME_TOKEN);
DECLARE @LEGACY_MAIN_CONTROL_NAME NVARCHAR(200) = N'ListPaneMenuAction' + @ACTION;
DECLARE @MODAL_DIALOG_NAME NVARCHAR(200) = ISNULL(@OVERRIDE_MODAL_DIALOG_NAME, N'UA_MDL_' + @ACTION_NAME_TOKEN);
DECLARE @LEGACY_MODAL_DIALOG_NAME NVARCHAR(200) = @ACTION + N'ModalDialog';
DECLARE @SCREEN_ID NUMERIC(9,0);
DECLARE @SCREEN_GROUP_ID NUMERIC(9,0);
DECLARE @MAIN_CONTROL_ID NUMERIC(9,0);
DECLARE @MAIN_EVENT_ID NUMERIC(9,0);
DECLARE @LIST_GRID_EVENT_ID NUMERIC(9,0);
DECLARE @MODAL_PART_ID NUMERIC(9,0);
DECLARE @MODAL BIT = 0;
DECLARE @CHECK_POINT INT;
DECLARE @CHECKPOINT_IN_USE BIT = 0;
DECLARE @ENABLE_ACTION_PARAM_NAME NVARCHAR(300) = N'EnableAction_' + @MAIN_CONTROL_NAME;

BEGIN TRY
	BEGIN TRANSACTION;

	PRINT N'=== User Action Remove Started ===';
	PRINT N'Form ID: ' + CAST(@FORM_ID AS NVARCHAR(20));
	PRINT N'Action: ' + @ACTION;

	SELECT
		@SCREEN_GROUP_ID = actions_group.OBJECT_ID,
		@SCREEN_ID = s.OBJECT_ID
	FROM MAIN_UI_SCREEN s
	OUTER APPLY (
		SELECT TOP 1 sp.OBJECT_ID
		FROM SCREEN_PART sp
		WHERE sp.SCREEN_ID = s.OBJECT_ID
			AND sp.PART_NAME = N'InsightMenuPane'
			AND sp.ACTIVE = N'Y'
	) AS menu_part
	OUTER APPLY (
		SELECT TOP 1 sg.OBJECT_ID
		FROM SCREEN_GROUP sg
		WHERE sg.SCREEN_PART_ID = menu_part.OBJECT_ID
			AND sg.GROUP_NAME = N'InsightMenuActionsDropdown'
			AND sg.ACTIVE = N'Y'
	) AS actions_group
	WHERE s.FORM_ID = @FORM_ID
	  AND s.ACTIVE = N'Y';

	IF @SCREEN_ID IS NULL OR @SCREEN_GROUP_ID IS NULL
		THROW 50001, 'Unable to locate active screen/actions dropdown for FORM_ID.', 1;

	PRINT N'Target screen found. SCREEN_ID=' + CAST(@SCREEN_ID AS NVARCHAR(20)) + N', ACTIONS_GROUP_ID=' + CAST(@SCREEN_GROUP_ID AS NVARCHAR(20));

	SELECT TOP 1 @MAIN_CONTROL_ID = OBJECT_ID
	FROM SCREEN_CONTROL
	WHERE SCREEN_GROUP_ID = @SCREEN_GROUP_ID
	  AND ACTIVE = N'Y'
	  AND (
	        CONTROL_NAME = @MAIN_CONTROL_NAME
	     OR CONTROL_NAME = @LEGACY_MAIN_CONTROL_NAME
	     OR RESOURCE_KEY = @RESOURCE_KEY
	  )
	ORDER BY CASE
	    WHEN CONTROL_NAME = @MAIN_CONTROL_NAME THEN 0
	    WHEN RESOURCE_KEY = @RESOURCE_KEY THEN 1
	    WHEN CONTROL_NAME = @LEGACY_MAIN_CONTROL_NAME THEN 2
	    ELSE 3
	END,
	OBJECT_ID DESC;

	IF @MAIN_CONTROL_ID IS NOT NULL
	BEGIN
		SELECT TOP 1 @MAIN_EVENT_ID = OBJECT_ID
		FROM SCREEN_CONTROL_EVENT
		WHERE SCREEN_CONTROL_ID = @MAIN_CONTROL_ID
		  AND EVENT_ID = N'click'
		  AND ACTIVE = N'Y'
		ORDER BY OBJECT_ID DESC;

		IF EXISTS (
			SELECT 1
			FROM SCREEN_CONTROL_EVENT_PARAMETERS
			WHERE SCREEN_CONTROL_EVENT_ID = @MAIN_EVENT_ID
			  AND PARAMETER_NAME = N'ModalDialogName'
			  AND ACTIVE = N'Y'
		)
		BEGIN
			SET @MODAL = 1;
		END

		PRINT N'Modal auto-detected from click event params: ' + CAST(@MODAL AS NVARCHAR(1));

		IF OBJECT_ID('tempdb..#MainEvents') IS NOT NULL DROP TABLE #MainEvents;
		CREATE TABLE #MainEvents (EVENT_ID INT NOT NULL PRIMARY KEY);

		INSERT INTO #MainEvents (EVENT_ID)
		SELECT OBJECT_ID
		FROM SCREEN_CONTROL_EVENT
		WHERE SCREEN_CONTROL_ID = @MAIN_CONTROL_ID;

		DELETE FROM SCREEN_CONTROL_EVENT_PARAMETERS
		WHERE SCREEN_CONTROL_EVENT_ID IN (SELECT EVENT_ID FROM #MainEvents);
		PRINT N'Deleted main control event parameters: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

		DELETE FROM SCREEN_CONTROL_EVENT
		WHERE OBJECT_ID IN (SELECT EVENT_ID FROM #MainEvents);
		PRINT N'Deleted main control events: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

		DELETE FROM SCREEN_CONTROL_ATTRIBUTES
		WHERE SCREEN_CONTROL_ID = @MAIN_CONTROL_ID;
		PRINT N'Deleted main control attributes: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

		DELETE FROM SCREEN_CONTROL
		WHERE OBJECT_ID = @MAIN_CONTROL_ID;
		PRINT N'Deleted main action control: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));
	END
	ELSE
	BEGIN
		PRINT N'Main action control not found. Skipping control/event cleanup.';
		PRINT N'Modal auto-detect skipped because main control was not found.';
	END

	SELECT @LIST_GRID_EVENT_ID = list_control_event.OBJECT_ID
	FROM MAIN_UI_SCREEN s
	OUTER APPLY (
		SELECT TOP 1 sp.OBJECT_ID
		FROM SCREEN_PART sp
		WHERE sp.SCREEN_ID = s.OBJECT_ID
			AND sp.PART_NAME = N'ListPane'
			AND sp.ACTIVE = N'Y'
	) AS list_part
	OUTER APPLY (
		SELECT TOP 1 sg.OBJECT_ID
		FROM SCREEN_GROUP sg
		WHERE sg.SCREEN_PART_ID = list_part.OBJECT_ID
			AND sg.GROUP_NAME = N'ListPanePanel'
			AND sg.ACTIVE = N'Y'
	) AS list_panel_group
	OUTER APPLY (
		SELECT TOP 1 sc.OBJECT_ID
		FROM SCREEN_CONTROL sc
		WHERE sc.SCREEN_GROUP_ID = list_panel_group.OBJECT_ID
			AND sc.CONTROL_NAME = N'ListPaneDataGrid'
			AND sc.ACTIVE = N'Y'
	) AS list_control
	OUTER APPLY (
		SELECT TOP 1 sce.OBJECT_ID
		FROM SCREEN_CONTROL_EVENT sce
		WHERE sce.SCREEN_CONTROL_ID = list_control.OBJECT_ID
			AND sce.EVENT_ID = N'iggridselectionactiverowchanged'
			AND sce.ACTIVE = N'Y'
	) AS list_control_event
	WHERE s.ACTIVE = N'Y'
	  AND s.FORM_ID = @FORM_ID;

	IF @LIST_GRID_EVENT_ID IS NOT NULL
	BEGIN
		DELETE FROM SCREEN_CONTROL_EVENT_PARAMETERS
		WHERE SCREEN_CONTROL_EVENT_ID = @LIST_GRID_EVENT_ID
		  AND PARAMETER_NAME = @ENABLE_ACTION_PARAM_NAME
		  AND ACTIVE = N'Y';

		PRINT N'Deleted active-row-change enable-action params: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));
	END
	ELSE
	BEGIN
		PRINT N'ListPaneDataGrid iggridselectionactiverowchanged event not found. Skipping active-row-change cleanup.';
	END

	IF @MODAL = 1
	BEGIN
		SELECT TOP 1 @MODAL_PART_ID = part.OBJECT_ID
		FROM SCREEN_PART part
		WHERE part.SCREEN_ID = @SCREEN_ID
		  AND (
		        part.PART_NAME = @MODAL_DIALOG_NAME
		     OR part.PART_NAME = @LEGACY_MODAL_DIALOG_NAME
		     OR EXISTS (
		            SELECT 1
		            FROM SCREEN_GROUP modal_group
		            WHERE modal_group.SCREEN_PART_ID = part.OBJECT_ID
		              AND modal_group.RESOURCE_KEY = @RESOURCE_KEY
		              AND modal_group.ACTIVE = N'Y'
		        )
		  )
		ORDER BY CASE
		    WHEN part.PART_NAME = @MODAL_DIALOG_NAME THEN 0
		    WHEN EXISTS (
		            SELECT 1
		            FROM SCREEN_GROUP modal_group
		            WHERE modal_group.SCREEN_PART_ID = part.OBJECT_ID
		              AND modal_group.RESOURCE_KEY = @RESOURCE_KEY
		              AND modal_group.ACTIVE = N'Y'
		        ) THEN 1
		    WHEN part.PART_NAME = @LEGACY_MODAL_DIALOG_NAME THEN 2
		    ELSE 3
		END,
		part.OBJECT_ID DESC;

		IF @MODAL_PART_ID IS NOT NULL
		BEGIN
			IF OBJECT_ID('tempdb..#ModalGroups') IS NOT NULL DROP TABLE #ModalGroups;
			IF OBJECT_ID('tempdb..#ModalControls') IS NOT NULL DROP TABLE #ModalControls;
			IF OBJECT_ID('tempdb..#ModalEvents') IS NOT NULL DROP TABLE #ModalEvents;

			CREATE TABLE #ModalGroups (GROUP_ID INT NOT NULL PRIMARY KEY);
			CREATE TABLE #ModalControls (CONTROL_ID INT NOT NULL PRIMARY KEY);
			CREATE TABLE #ModalEvents (EVENT_ID INT NOT NULL PRIMARY KEY);

			INSERT INTO #ModalGroups (GROUP_ID)
			SELECT OBJECT_ID
			FROM SCREEN_GROUP
			WHERE SCREEN_PART_ID = @MODAL_PART_ID;

			INSERT INTO #ModalControls (CONTROL_ID)
			SELECT OBJECT_ID
			FROM SCREEN_CONTROL
			WHERE SCREEN_GROUP_ID IN (SELECT GROUP_ID FROM #ModalGroups);

			INSERT INTO #ModalEvents (EVENT_ID)
			SELECT OBJECT_ID
			FROM SCREEN_CONTROL_EVENT
			WHERE SCREEN_CONTROL_ID IN (SELECT CONTROL_ID FROM #ModalControls);

			DELETE FROM SCREEN_CONTROL_EVENT_PARAMETERS
			WHERE SCREEN_CONTROL_EVENT_ID IN (SELECT EVENT_ID FROM #ModalEvents);
			PRINT N'Deleted modal event parameters: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

			DELETE FROM SCREEN_CONTROL_EVENT
			WHERE OBJECT_ID IN (SELECT EVENT_ID FROM #ModalEvents);
			PRINT N'Deleted modal events: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

			DELETE FROM SCREEN_CONTROL_ATTRIBUTES
			WHERE SCREEN_CONTROL_ID IN (SELECT CONTROL_ID FROM #ModalControls);
			PRINT N'Deleted modal control attributes: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

			DELETE FROM SCREEN_CONTROL
			WHERE OBJECT_ID IN (SELECT CONTROL_ID FROM #ModalControls);
			PRINT N'Deleted modal controls: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

			DELETE FROM SCREEN_GROUP
			WHERE OBJECT_ID IN (SELECT GROUP_ID FROM #ModalGroups);
			PRINT N'Deleted modal groups: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

			DELETE FROM SCREEN_PART
			WHERE OBJECT_ID = @MODAL_PART_ID;
			PRINT N'Deleted modal part: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));
		END
		ELSE
		BEGIN
			PRINT N'Modal part not found. Skipping modal cleanup.';
		END
	END

	SELECT @CHECK_POINT = CHECK_POINT
	FROM SECURITY_CHECKPOINT
	WHERE FORM_ID = @FORM_ID
	  AND RESOURCE_FILE_KEY = @RESOURCE_KEY;

	IF @CHECK_POINT IS NOT NULL
	BEGIN
		IF EXISTS (
			SELECT 1
			FROM SCREEN_CONTROL_ATTRIBUTES sca
			INNER JOIN SCREEN_CONTROL sc ON sc.OBJECT_ID = sca.SCREEN_CONTROL_ID
			INNER JOIN SCREEN_GROUP sg ON sg.OBJECT_ID = sc.SCREEN_GROUP_ID
			INNER JOIN SCREEN_PART sp ON sp.OBJECT_ID = sg.SCREEN_PART_ID
			INNER JOIN MAIN_UI_SCREEN ms ON ms.OBJECT_ID = sp.SCREEN_ID
			WHERE ms.FORM_ID = @FORM_ID
			  AND sca.ATTRIBUTE_NAME = N'data-securityCheckpoint'
			  AND sca.ATTRIBUTE_VALUE = CAST(@CHECK_POINT AS NVARCHAR(50))
			  AND sca.ACTIVE = N'Y'
			  AND sc.ACTIVE = N'Y'
			  AND sg.ACTIVE = N'Y'
			  AND sp.ACTIVE = N'Y'
			  AND ms.ACTIVE = N'Y'
		)
		BEGIN
			SET @CHECKPOINT_IN_USE = 1;
		END

		IF @CHECKPOINT_IN_USE = 0
		BEGIN
			UPDATE SECURITY
			SET SEC_VALUES = CASE
				WHEN LEN(SEC_VALUES) >= @CHECK_POINT THEN STUFF(SEC_VALUES, @CHECK_POINT, 1, N'')
				ELSE SEC_VALUES
			END
			WHERE FORM_ID = @FORM_ID;
			PRINT N'Updated SECURITY SEC_VALUES for removed checkpoint: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

			DELETE FROM SECURITY_CHECKPOINT
			WHERE FORM_ID = @FORM_ID
			  AND CHECK_POINT = @CHECK_POINT
			  AND RESOURCE_FILE_KEY = @RESOURCE_KEY;
			PRINT N'Deleted SECURITY_CHECKPOINT rows: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

			UPDATE SECURITY_CHECKPOINT
			SET CHECK_POINT = CHECK_POINT - 1
			WHERE FORM_ID = @FORM_ID
			  AND CHECK_POINT > @CHECK_POINT;
			PRINT N'Resequenced SECURITY_CHECKPOINT rows: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));
		END
		ELSE
		BEGIN
			PRINT N'Security checkpoint still referenced by active controls. Checkpoint retained.';
		END
	END
	ELSE
	BEGIN
		PRINT N'No checkpoint found for resource key. Skipping checkpoint cleanup.';
	END

	COMMIT TRANSACTION;

	PRINT N'=== User Action Remove Completed Successfully ===';
	PRINT N'Resource key was intentionally preserved: ' + @RESOURCE_KEY;
END TRY
BEGIN CATCH
	IF XACT_STATE() <> 0
		ROLLBACK TRANSACTION;

	DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
	DECLARE @ErrNum INT = ERROR_NUMBER();
	DECLARE @ErrLine INT = ERROR_LINE();
	DECLARE @ErrProc NVARCHAR(200) = ERROR_PROCEDURE();

	PRINT N'=== User Action Remove Failed ===';
	PRINT N'Error Number: ' + CAST(@ErrNum AS NVARCHAR(20));
	PRINT N'Error Line: ' + CAST(@ErrLine AS NVARCHAR(20));
	PRINT N'Error Procedure: ' + ISNULL(@ErrProc, N'<dynamic SQL / batch>');
	PRINT N'Error Message: ' + @ErrMsg;

	THROW;
END CATCH;
